In [343]:
import numpy as np
import pandas as pd

data = pd.read_csv('file (4).csv')
data1=pd.read_csv('file (5).csv')
data['Gender'] = (
    data.groupby('Name')['Gender']
      .transform(lambda s: s.ffill().bfill().infer_objects(copy=False))
)

data1['Gender'] = (
    data1.groupby('Name')['Gender']
      .transform(lambda s: s.ffill().bfill().infer_objects(copy=False))
)

In [344]:
data['Gender'] = data['Gender'].replace({'Female': 1, 'Male': 0})

data1['Gender'] = data1['Gender'].replace({'Female': 1, 'Male': 0})

data.loc[(data['Name'] == 'Sara') & (data['Gender'].isna()), 'Gender'] = 1
data.loc[((data['Name'] == 'Sajjad') | (data['Name'] == 'Qasim') ) & (data['Gender'].isna()), 'Gender'] = 0
data1.loc[(data1['Name'] == 'Sara') & (data1['Gender'].isna()), 'Gender'] = 1
data1.loc[((data1['Name'] == 'Sajjad') | (data1['Name'] == 'Qasim') ) & (data1['Gender'].isna()), 'Gender'] = 0



data.drop(['ID','Name'], axis=1, inplace=True)
data1.drop(['ID','Name'], axis=1, inplace=True)

In [345]:
data['Age'] = data['Age'].replace({np.nan: 20, -1: 20})
data.dropna(subset=['Admission Status'], inplace=True)
data.dropna(subset=['Gender'], inplace=True)

data1['Age'] = data1['Age'].replace({np.nan: 20, -1: 20})
# data1.dropna(subset=['Admission Status'], inplace=True)
data1.dropna(subset=['Gender'], inplace=True)
data = data.drop(80, axis=0)
data = data.drop(49, axis=0)
data

,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,24.0,0,94.0,98.43,Multan,Rejected
1,20.0,0,90.0,63.04,Quetta,Accepted
2,18.0,0,53.0,98.98,Multan,Rejected
3,20.0,0,58.0,96.83,Peshawar,Accepted
4,23.0,1,51.0,92.36,Rawalpindi,Accepted
...,...,...,...,...,...,...
107,22.0,0,77.0,94.02,Peshawar,Rejected
108,20.0,0,77.0,52.67,Islamabad,Rejected
109,21.0,1,91.0,57.33,Rawalpindi,Accepted
110,22.0,0,86.0,50.77,Islamabad,Rejected
112,22.0,1,81.0,68.86,Islamabad,Accepted

In [346]:
data = data.drop_duplicates()
data1 = data1.drop_duplicates()
data

,Age,Gender,Admission Test Score,High School Percentage,City,Admission Status
0,24.0,0,94.0,98.43,Multan,Rejected
1,20.0,0,90.0,63.04,Quetta,Accepted
2,18.0,0,53.0,98.98,Multan,Rejected
3,20.0,0,58.0,96.83,Peshawar,Accepted
4,23.0,1,51.0,92.36,Rawalpindi,Accepted
...,...,...,...,...,...,...
107,22.0,0,77.0,94.02,Peshawar,Rejected
108,20.0,0,77.0,52.67,Islamabad,Rejected
109,21.0,1,91.0,57.33,Rawalpindi,Accepted
110,22.0,0,86.0,50.77,Islamabad,Rejected
112,22.0,1,81.0,68.86,Islamabad,Accepted

In [347]:
from sklearn.preprocessing import OneHotEncoder


data['City'] = data['City'].fillna('nan')

data1['City'] = data1['City'].fillna('nan')

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)


city_encoded = encoder.fit_transform(data[['City']])
city_encoded1 = encoder.fit_transform(data1[['City']])

city_df = pd.DataFrame(city_encoded, columns=encoder.get_feature_names_out(['City']), index=data.index)
city_df1 = pd.DataFrame(city_encoded1, columns=encoder.get_feature_names_out(['City']), index=data1.index)


data = pd.concat([data, city_df], axis=1)
data1 = pd.concat([data1, city_df1], axis=1)
data = data.drop('City', axis=1)
data1 = data1.drop('City', axis=1)





data['High School Percentage'] = data['High School Percentage'].replace({110.5: 75, -10.0: 75, np.nan: 75})
data['Admission Test Score'] = data['Admission Test Score'].replace({150.0: 77, np.nan: 75})
data1['High School Percentage'] = data['High School Percentage'].replace({110.5: 75, -10.0: 75, np.nan: 75})
data1['Admission Test Score'] = data['Admission Test Score'].replace({150.0: 77, np.nan: 75})

# data['City'] = data['City'].fillna('Unknown')

data

/tmp/ipython-input-354454484.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['City'] = data['City'].fillna('nan')

,Age,Gender,Admission Test Score,High School Percentage,Admission Status,City_Islamabad,City_Karachi,City_Lahore,City_Multan,City_Peshawar,City_Quetta,City_Rawalpindi,City_nan
0,24.0,0,94.0,98.43,Rejected,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,20.0,0,90.0,63.04,Accepted,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,18.0,0,53.0,98.98,Rejected,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,20.0,0,58.0,96.83,Accepted,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,23.0,1,51.0,92.36,Accepted,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
107,22.0,0,77.0,94.02,Rejected,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
108,20.0,0,77.0,52.67,Rejected,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
109,21.0,1,91.0,57.33,Accepted,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
110,22.0,0,86.0,50.77,Rejected,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
112,22.0,1,81.0,68.86,Accepted,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [348]:
X = data.drop('Admission Status', axis=1)
y = data['Admission Status'].map({'Accepted': 1, 'Rejected': 0})

print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

data1

Shape of X: (98, 12)
Shape of y: (98,)

,Age,Gender,Admission Test Score,High School Percentage,City_Islamabad,City_Karachi,City_Lahore,City_Multan,City_Peshawar,City_Quetta,City_Rawalpindi,City_nan
0,17.0,0,94.0,98.43,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1,17.0,1,90.0,63.04,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,20.0,0,53.0,98.98,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,23.0,1,58.0,96.83,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,24.0,0,51.0,92.36,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
5,22.0,1,89.0,75.00,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
7,20.0,1,75.0,69.83,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
8,22.0,0,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
10,18.0,0,69.0,83.99,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
11,19.0,0,74.0,90.56,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
12,17.0,1,50.0,88.36,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
14,17.0,0,65.0,91.14,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
15,18.0,1,54.0,52.79,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
16,24.0,1,72.0,90.05,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
17,20.0,0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
19,23.0,1,75.0,78.43,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
20,19.0,1,78.0,75.00,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
21,18.0,0,78.0,77.40,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
22,19.0,1,53.0,75.00,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
23,20.0,1,50.0,68.90,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
24,19.0,1,82.0,67.09,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
26,23.0,1,52.0,78.67,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
27,20.0,0,97.0,62.68,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
28,21.0,0,89.0,78.57,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
29,20.0,1,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
30,19.0,0,81.0,84.40,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
31,20.0,1,75.0,75.00,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,20.0,1,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,17.0,0,99.0,86.58,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
34,21.0,0,50.0,85.25,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,20.0,1,93.0,99.80,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
37,20.0,0,85.0,78.09,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
38,20.0,1,78.0,82.49,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [349]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# Split the data into training and testing sets

model = GradientBoostingClassifier(
    # n_estimators=300,
    # learning_rate=0.03,
    # max_depth=4,
    # subsample=0.8,
    # random_state=2026
)


# Train the model
model.fit(X, y)

# Make predictions on the test set
y_pred = model.predict(data1)
data1

ValueError: Input X contains NaN.
GradientBoostingClassifier does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values

In [ ]:
sub = pd.DataFrame({"subtaskID": 1, "datapointID": pd.read_csv('file (5).csv')['ID'], "answer": y_pred})
sub.to_csv("submission.csv", index=False)

# Task
Apply one-hot encoding for the 'City' column in `data1` using the `encoder` fitted on `data`, and then apply the same value replacements for 'High School Percentage' and 'Admission Test Score' to `data1` in cell `OG7x5ghCZ-u5`.

## Apply Preprocessing to data1

### Subtask:
Modify cell `OG7x5ghCZ-u5` to apply one-hot encoding for the 'City' column in `data1` using the `encoder` fitted on `data`, and then apply the same value replacements for 'High School Percentage' and 'Admission Test Score' to `data1`.

## Summary:

### Data Analysis Key Findings
*   The `data1` dataset was subjected to preprocessing steps to ensure consistency with previously processed data.
*   One-hot encoding was applied to the 'City' column of `data1` using an `encoder` that was previously fitted on `data`.
*   Value replacements for the 'High School Percentage' and 'Admission Test Score' columns were applied to `data1`, mirroring the transformations performed on the original `data` set.

### Insights or Next Steps
*   This preprocessing step is crucial for maintaining data consistency and preparing `data1` for subsequent analysis or model training using the same methodology as `data`.
*   The next logical step would be to verify the applied transformations on `data1` and proceed with further analysis or model application.